#!define GAMEMODE_VERSION "Dev Build"
#!define GAMEMODE_NAME "6v6 Adjustments"
#!define SOURCE_CODE_LINK "github.com/6v6-Adjustments/6v6-adjustments"
#!define GAMEMODE_CODE "7HSKW"
macro GAMDMODE_DESCRIPTION = (GAMEMODE_NAME" "GAMEMODE_VERSION" ("GAMEMODE_CODE")\n"\
                               "\n"\
                               "Overwatch 2 adjusted for 6v6 gameplay""\n"\
                               "by Toastie#11770 and ecksdee#11729""\n"\
                               "\n"\
                               "Developers:""\n"\
                               "ecksdee#11729""\n"\
                               "Toastie#11770""\n"\
                               "LemonHead#11820""\n"\
                               "\n"\
                               "OverPy codebase forked from""\n"\
                               "Overwatch 1 Emulator v1.12.2 (KHTG0)""\n"\
                               "by ecksdee#11729""\n"\
                               "\n"\
                               SOURCE_CODE_LINK)